name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
      env:
        SUPER_SECRET: ${{ secrets.MODELLER_LICENSE_KEY }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        export KEY_MODELLER=$MODELLER_LICENSE_KEY

        conda install -c salilab modeller
        # This may be slower but saves us from having to build gromacs
        sed -i -e "s/XXXX/$MODELLER_LICENSE_KEY/g" /usr/share/miniconda/lib/modeller-*/modlib/modeller/config.py
        
        # Delete this as soon as not needed!
        cat /usr/share/miniconda/lib/modeller-10.4/modlib/modeller/config.py
        
        conda install -c bioconda gromacs
        
    - name: Install PyMEMENTO
      run: |
        pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
