name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      shell: bash
      env:
           LICENSE_KEY: ${{ secrets.MODELLER_LICENSE_KEY }}
      run: |

        conda install -c salilab modeller
        
        sed -i -e "s/XXXX/${LICENSE_KEY}/g" /usr/share/miniconda/lib/modeller-*/modlib/modeller/config.py
        
        # Delete this as soon as not needed!
        cat /usr/share/miniconda/lib/modeller-10.4/modlib/modeller/config.py
        
        # This may be slower but saves us from having to build gromacs
        conda install libgcc-ng>=11.2.0
        conda install -c bioconda gromacs=2021.3
        
    - name: Install PyMEMENTO
      run: |
        pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
