name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
      env:
        SUPER_SECRET: ${{ secrets.MODELLER_LICENSE_KEY }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
        # Fixing the version so that the license key location stays up to date
        conda install modeller
        
        # install the modeller secret
        sed -i -e "s/XXXX/$MODELLER_LICENSE_KEY/g"  $CONDA/lib/modeller-*/modlib/modeller/config.py
        
        # This may be slower but saves us from having to build gromacs
        conda install -c bioconda gromacs
        
    - name: Install PyMEMENTO
      run: |
        pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
